[Info]
TopPageInfo = "# cmd\n一些 shell 脚本  \nproxy.fxtaoo.dev 是使用 Cloudflare CDN 代理 raw.githubusercontent.com"
CodeURL = "https://github.com/fxtaoo/cmd/blob/master/"
GithubRaw = "https://raw.githubusercontent.com/fxtaoo/cmd/master/"
FxtaooRaw = "https://proxy.fxtaoo.dev/raw/fxtaoo/cmd/master/"
DirInfo = [["func", "函数"],["sys", "系统"],["install", "安装"],["other","其他"]]